using System.Text;
using CulpeoStream.SourceGen.Models;

namespace CulpeoStream.SourceGen.Generators;

/// <summary>
/// Generates partial class source code for a <see cref="HandlerDescriptor"/>.
/// All generated code is NativeAOT-safe: no reflection, no <c>dynamic</c>.
/// </summary>
internal static class CodeGenerator
{
    public static string Generate(HandlerDescriptor descriptor)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by CulpeoStream.SourceGen — do not modify manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(descriptor.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(descriptor.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        string indent = hasNamespace ? "    " : "";

        // F9: emit a doc comment explaining that protocol events are middleware-handled
        sb.Append(indent).AppendLine("/// <summary>");
        sb.Append(indent).AppendLine("/// Generated CulpeoStream dispatch infrastructure for this handler.");
        sb.Append(indent).AppendLine("/// <para>");
        sb.Append(indent).AppendLine("/// <b>Note:</b> Protocol events (<c>culpeo.*</c>) are consumed by the");
        sb.Append(indent).AppendLine("/// CulpeoStream middleware before reaching application code and will");
        sb.Append(indent).AppendLine("/// <em>never</em> be passed to <see cref=\"OnMessageAsync\"/>.");
        sb.Append(indent).AppendLine("/// Only application-defined events (non-<c>culpeo.</c> namespace) are routed here.");
        sb.Append(indent).AppendLine("/// </para>");
        sb.Append(indent).AppendLine("/// </summary>");
        sb.Append(indent).Append("partial class ").AppendLine(descriptor.ClassName);
        sb.Append(indent).AppendLine("{");

        string i2 = indent + "    ";
        string i3 = indent + "        ";
        string i4 = indent + "            ";

        // ── RegisteredStreams ──────────────────────────────────────────────

        sb.Append(i2).AppendLine("// ── RegisteredStreams (NativeAOT-safe, populated at compile-time) ─────────────");
        sb.Append(i2).AppendLine("private static readonly global::System.Collections.Generic.IReadOnlyList<global::CulpeoStream.Core.StreamDeclaration> _culpeo_registeredStreams =");

        if (descriptor.Streams.Length == 0)
        {
            sb.Append(i3).AppendLine("global::System.Array.Empty<global::CulpeoStream.Core.StreamDeclaration>();");
        }
        else
        {
            sb.Append(i3).AppendLine("new global::CulpeoStream.Core.StreamDeclaration[]");
            sb.Append(i3).AppendLine("{");
            foreach (var stream in descriptor.Streams)
            {
                var streamTypeExpr = StreamTypeExpression(stream.StreamType);
                var offsetTypeExpr = OffsetTypeExpression(stream.OffsetType);
                var purposeExpr = stream.Purpose is null ? "null" : $"\"{EscapeString(stream.Purpose)}\"";
                sb.Append(i4).AppendLine("new global::CulpeoStream.Core.StreamDeclaration");
                sb.Append(i4).AppendLine("{");
                sb.Append(i4).Append("    ContentType = \"").Append(EscapeString(stream.ContentType)).AppendLine("\",");
                sb.Append(i4).Append("    Type = ").Append(streamTypeExpr).AppendLine(",");
                sb.Append(i4).Append("    OffsetType = ").Append(offsetTypeExpr).AppendLine(",");
                sb.Append(i4).Append("    Purpose = ").Append(purposeExpr).AppendLine(",");
                sb.Append(i4).AppendLine("},");
            }
            sb.Append(i3).AppendLine("};");
        }

        sb.AppendLine();
        sb.Append(i2).AppendLine("/// <summary>");
        sb.Append(i2).AppendLine("/// Streams declared on this handler via <c>[DeclareStream]</c>.");
        sb.Append(i2).AppendLine("/// Populated at compile-time — NativeAOT-safe, no runtime reflection.");
        sb.Append(i2).AppendLine("/// </summary>");
        sb.Append(i2).AppendLine("public global::System.Collections.Generic.IReadOnlyList<global::CulpeoStream.Core.StreamDeclaration> RegisteredStreams");
        sb.Append(i2).AppendLine("    => _culpeo_registeredStreams;");

        // ── F1: Stream ID resolution map (hint → server-assigned ID) ──────

        if (descriptor.Streams.Length > 0)
        {
            sb.AppendLine();
            sb.Append(i2).AppendLine("// ── F1: hint→assigned-ID map (populated by CulpeoRegisterStreamIds) ──────────");
            sb.Append(i2).AppendLine("/// <summary>Maps each <c>[DeclareStream]</c> hint to the server-assigned stream ID.</summary>");
            sb.Append(i2).AppendLine("private readonly global::System.Collections.Generic.Dictionary<string, string> _culpeo_streamIdMap =");
            sb.Append(i3).AppendLine("new global::System.Collections.Generic.Dictionary<string, string>(global::System.StringComparer.Ordinal);");

            sb.AppendLine();
            sb.Append(i2).AppendLine("/// <summary>");
            sb.Append(i2).AppendLine("/// Resolves the server-assigned stream IDs by matching declared streams to the");
            sb.Append(i2).AppendLine("/// session's confirmed stream list. Call this from");
            sb.Append(i2).AppendLine("/// <see cref=\"global::CulpeoStream.AspNetCore.ICulpeoStreamHandler.OnConnectedAsync\"/>");
            sb.Append(i2).AppendLine("/// so that <see cref=\"HandleMediaAsync\"/> can dispatch correctly.");
            sb.Append(i2).AppendLine("/// </summary>");
            sb.Append(i2).AppendLine("protected void CulpeoRegisterStreamIds(global::CulpeoStream.AspNetCore.ICulpeoStreamSession session)");
            sb.Append(i2).AppendLine("{");
            sb.Append(i3).AppendLine("_culpeo_streamIdMap.Clear();");
            sb.Append(i3).AppendLine("foreach (var stream in session.Streams)");
            sb.Append(i3).AppendLine("{");
            foreach (var stream in descriptor.Streams)
            {
                var streamTypeExpr = StreamTypeExpression(stream.StreamType);
                var offsetTypeExpr = OffsetTypeExpression(stream.OffsetType);
                var purposeCheck = stream.Purpose is null
                    ? "stream.Purpose is null"
                    : $"stream.Purpose == \"{EscapeString(stream.Purpose)}\"";
                sb.Append(i4).AppendLine($"if (stream.ContentType == \"{EscapeString(stream.ContentType)}\"");
                sb.Append(i4).AppendLine($"    && stream.Type == {streamTypeExpr}");
                sb.Append(i4).AppendLine($"    && {purposeCheck}");
                sb.Append(i4).AppendLine($"    && !_culpeo_streamIdMap.ContainsKey(\"{EscapeString(stream.Id)}\"))");
                sb.Append(i4).AppendLine("{");
                sb.Append(i4).AppendLine($"    _culpeo_streamIdMap[\"{EscapeString(stream.Id)}\"] = stream.Id;");
                sb.Append(i4).AppendLine("    continue;");
                sb.Append(i4).AppendLine("}");
            }
            sb.Append(i3).AppendLine("}");
            sb.Append(i2).AppendLine("}");
        }

        // ── OnMessageAsync ────────────────────────────────────────────────

        sb.AppendLine();
        sb.Append(i2).AppendLine("// ── OnMessageAsync — generated switch-expression dispatch (no dictionary, no reflection) ─");
        sb.Append(i2).AppendLine("/// <summary>");
        sb.Append(i2).AppendLine("/// Dispatches an incoming application event by name to the appropriate typed virtual method.");
        sb.Append(i2).AppendLine("/// Protocol events (<c>culpeo.*</c>) are handled by the middleware and will never");
        sb.Append(i2).AppendLine("/// reach this method. Call this from <see cref=\"global::CulpeoStream.AspNetCore.ICulpeoStreamHandler.OnEventAsync\"/>.");
        sb.Append(i2).AppendLine("/// </summary>");
        sb.Append(i2).AppendLine("public global::System.Threading.Tasks.Task OnMessageAsync(");
        sb.Append(i2).AppendLine("    string eventName,");
        sb.Append(i2).AppendLine("    string jsonBody,");
        sb.Append(i2).AppendLine("    string? streamId,");
        sb.Append(i2).AppendLine("    global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append(i2).AppendLine("    => eventName switch");
        sb.Append(i2).AppendLine("    {");
        // F9: no culpeo.* arms — those are middleware-only
        sb.Append(i3).AppendLine("_ => OnUnknownEventAsync(eventName, jsonBody, streamId, cancellationToken),");
        sb.Append(i2).AppendLine("    };");

        // ── HandleMediaAsync ──────────────────────────────────────────────

        sb.AppendLine();
        sb.Append(i2).AppendLine("// ── HandleMediaAsync — dispatches by server-assigned stream ID via CulpeoRegisterStreamIds ─");
        sb.Append(i2).AppendLine("/// <summary>");
        sb.Append(i2).AppendLine("/// Routes an incoming media frame to the appropriate per-stream virtual method.");
        sb.Append(i2).AppendLine("/// Requires that <see cref=\"CulpeoRegisterStreamIds\"/> was called in");
        sb.Append(i2).AppendLine("/// <c>OnConnectedAsync</c> so that server-assigned IDs are known.");
        sb.Append(i2).AppendLine("/// Call this from <see cref=\"global::CulpeoStream.AspNetCore.ICulpeoStreamHandler.OnMediaFrameAsync\"/>.");
        sb.Append(i2).AppendLine("/// </summary>");
        sb.Append(i2).AppendLine("public global::System.Threading.Tasks.Task HandleMediaAsync(");
        sb.Append(i2).AppendLine("    string streamId,");
        sb.Append(i2).AppendLine("    global::System.ReadOnlyMemory<byte> payload,");
        sb.Append(i2).AppendLine("    long offset,");
        sb.Append(i2).AppendLine("    global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append(i2).AppendLine("{");

        if (descriptor.Streams.Length == 0)
        {
            // No declared streams — everything falls through
            sb.Append(i3).AppendLine("return OnUnknownStreamAsync(streamId, payload, offset, cancellationToken);");
        }
        else
        {
            // F1: reverse-lookup: find the hint whose assigned ID matches the incoming streamId,
            // then dispatch by hint. O(n) linear scan over a small set (1–16 streams).
            sb.Append(i3).AppendLine("string? hint = null;");
            sb.Append(i3).AppendLine("foreach (var kv in _culpeo_streamIdMap)");
            sb.Append(i3).AppendLine("{");
            sb.Append(i4).AppendLine("if (global::System.StringComparer.Ordinal.Equals(kv.Value, streamId)) { hint = kv.Key; break; }");
            sb.Append(i3).AppendLine("}");
            sb.Append(i3).AppendLine("return hint switch");
            sb.Append(i3).AppendLine("{");
            foreach (var stream in descriptor.Streams)
            {
                var methodName = $"On{stream.SafeMethodSuffix}Async";
                sb.Append(i4).Append($"\"{EscapeString(stream.Id)}\" => {methodName}(payload, offset, cancellationToken),").AppendLine();
            }
            sb.Append(i4).AppendLine("_ => OnUnknownStreamAsync(streamId, payload, offset, cancellationToken),");
            sb.Append(i3).AppendLine("};");
        }

        sb.Append(i2).AppendLine("}");

        // ── Virtual stub for unknown events ───────────────────────────────

        sb.AppendLine();
        sb.Append(i2).AppendLine("// ── Event handler stub — override to handle application events ───────────────");

        sb.Append(i2).AppendLine("/// <summary>Called for unrecognised (application-defined) event names. Override to handle custom application events.</summary>");
        sb.Append(i2).AppendLine("protected virtual global::System.Threading.Tasks.Task OnUnknownEventAsync(string eventName, string jsonBody, string? streamId, global::System.Threading.CancellationToken cancellationToken)");
        sb.Append(i2).AppendLine("    => global::System.Threading.Tasks.Task.CompletedTask;");

        // ── Per-stream media stubs ────────────────────────────────────────

        if (descriptor.Streams.Length > 0)
        {
            sb.AppendLine();
            sb.Append(i2).AppendLine("// ── Per-stream media handler stubs — override to process media frames ────────");

            foreach (var stream in descriptor.Streams)
            {
                var methodName = $"On{stream.SafeMethodSuffix}Async";
                sb.Append(i2).AppendLine($"/// <summary>Called for media frames on stream <c>\"{EscapeString(stream.Id)}\"</c> ({stream.ContentType}). Override to process frames.</summary>");
                sb.Append(i2).AppendLine($"protected virtual global::System.Threading.Tasks.Task {methodName}(global::System.ReadOnlyMemory<byte> payload, long offset, global::System.Threading.CancellationToken cancellationToken)");
                sb.Append(i2).AppendLine($"    => global::System.Threading.Tasks.Task.CompletedTask;");
                sb.AppendLine();
            }
        }

        sb.AppendLine();
        sb.Append(i2).AppendLine("/// <summary>Called for media frames on unknown or unregistered stream IDs.</summary>");
        sb.Append(i2).AppendLine("protected virtual global::System.Threading.Tasks.Task OnUnknownStreamAsync(string streamId, global::System.ReadOnlyMemory<byte> payload, long offset, global::System.Threading.CancellationToken cancellationToken)");
        sb.Append(i2).AppendLine("    => global::System.Threading.Tasks.Task.CompletedTask;");

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string StreamTypeExpression(int streamType) => streamType switch
    {
        0 => "global::CulpeoStream.Core.CulpeoStreamType.Input",
        1 => "global::CulpeoStream.Core.CulpeoStreamType.Output",
        2 => "global::CulpeoStream.Core.CulpeoStreamType.Duplex",
        _ => "global::CulpeoStream.Core.CulpeoStreamType.Input",
    };

    private static string OffsetTypeExpression(int offsetType) => offsetType switch
    {
        0 => "global::CulpeoStream.Core.OffsetType.Time",
        1 => "global::CulpeoStream.Core.OffsetType.Byte",
        2 => "global::CulpeoStream.Core.OffsetType.Message",
        _ => "global::CulpeoStream.Core.OffsetType.Byte",
    };

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
