using System.Text;
using CulpeoStream.SourceGen.Models;

namespace CulpeoStream.SourceGen.Generators;

/// <summary>
/// Generates partial class source code for a <see cref="HandlerDescriptor"/>.
/// All generated code is NativeAOT-safe: no reflection, no <c>dynamic</c>.
/// </summary>
internal static class CodeGenerator
{
    private static readonly string[] ProtocolEvents =
    [
        "culpeo.init",
        "culpeo.init-ack",
        "culpeo.init-error",
        "culpeo.ping",
        "culpeo.pong",
        "culpeo.auth-refresh",
        "culpeo.auth-response",
        "culpeo.close",
    ];

    public static string Generate(HandlerDescriptor descriptor)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by CulpeoStream.SourceGen — do not modify manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(descriptor.Namespace);
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(descriptor.Namespace).AppendLine();
            sb.AppendLine("{");
        }

        string indent = hasNamespace ? "    " : "";

        sb.Append(indent).Append("partial class ").AppendLine(descriptor.ClassName);
        sb.Append(indent).AppendLine("{");

        string i2 = indent + "    ";
        string i3 = indent + "        ";
        string i4 = indent + "            ";

        // ── RegisteredStreams ──────────────────────────────────────────────

        sb.Append(i2).AppendLine("// ── RegisteredStreams (NativeAOT-safe, populated at compile-time) ─────────────");
        sb.Append(i2).AppendLine("private static readonly global::System.Collections.Generic.IReadOnlyList<global::CulpeoStream.Core.StreamDeclaration> _culpeo_registeredStreams =");

        if (descriptor.Streams.Length == 0)
        {
            sb.Append(i3).AppendLine("global::System.Array.Empty<global::CulpeoStream.Core.StreamDeclaration>();");
        }
        else
        {
            sb.Append(i3).AppendLine("new global::CulpeoStream.Core.StreamDeclaration[]");
            sb.Append(i3).AppendLine("{");
            foreach (var stream in descriptor.Streams)
            {
                var streamTypeExpr = StreamTypeExpression(stream.StreamType);
                var offsetTypeExpr = OffsetTypeExpression(stream.OffsetType);
                var purposeExpr = stream.Purpose is null ? "null" : $"\"{EscapeString(stream.Purpose)}\"";
                sb.Append(i4).AppendLine("new global::CulpeoStream.Core.StreamDeclaration");
                sb.Append(i4).AppendLine("{");
                sb.Append(i4).Append("    ContentType = \"").Append(EscapeString(stream.ContentType)).AppendLine("\",");
                sb.Append(i4).Append("    Type = ").Append(streamTypeExpr).AppendLine(",");
                sb.Append(i4).Append("    OffsetType = ").Append(offsetTypeExpr).AppendLine(",");
                sb.Append(i4).Append("    Purpose = ").Append(purposeExpr).AppendLine(",");
                sb.Append(i4).AppendLine("},");
            }
            sb.Append(i3).AppendLine("};");
        }

        sb.AppendLine();
        sb.Append(i2).AppendLine("/// <summary>");
        sb.Append(i2).AppendLine("/// Streams declared on this handler via <c>[DeclareStream]</c>.");
        sb.Append(i2).AppendLine("/// Populated at compile-time — NativeAOT-safe, no runtime reflection.");
        sb.Append(i2).AppendLine("/// </summary>");
        sb.Append(i2).AppendLine("public global::System.Collections.Generic.IReadOnlyList<global::CulpeoStream.Core.StreamDeclaration> RegisteredStreams");
        sb.Append(i2).AppendLine("    => _culpeo_registeredStreams;");

        // ── OnMessageAsync ────────────────────────────────────────────────

        sb.AppendLine();
        sb.Append(i2).AppendLine("// ── OnMessageAsync — generated switch-expression dispatch (no dictionary, no reflection) ─");
        sb.Append(i2).AppendLine("/// <summary>");
        sb.Append(i2).AppendLine("/// Dispatches an incoming event by name to the appropriate typed virtual method.");
        sb.Append(i2).AppendLine("/// Call this from <see cref=\"global::CulpeoStream.AspNetCore.ICulpeoStreamHandler.OnEventAsync\"/>.");
        sb.Append(i2).AppendLine("/// </summary>");
        sb.Append(i2).AppendLine("public global::System.Threading.Tasks.Task OnMessageAsync(");
        sb.Append(i2).AppendLine("    string eventName,");
        sb.Append(i2).AppendLine("    string jsonBody,");
        sb.Append(i2).AppendLine("    string? streamId,");
        sb.Append(i2).AppendLine("    global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append(i2).AppendLine("    => eventName switch");
        sb.Append(i2).AppendLine("    {");
        foreach (var evt in ProtocolEvents)
        {
            var methodName = EventToMethodName(evt);
            sb.Append(i3).Append($"\"{evt}\" => {methodName}(jsonBody, cancellationToken),").AppendLine();
        }
        sb.Append(i3).AppendLine("_ => OnUnknownEventAsync(eventName, jsonBody, streamId, cancellationToken),");
        sb.Append(i2).AppendLine("    };");

        // ── HandleMediaAsync ──────────────────────────────────────────────

        sb.AppendLine();
        sb.Append(i2).AppendLine("// ── HandleMediaAsync — generated switch dispatch over stream IDs ──────────────");
        sb.Append(i2).AppendLine("/// <summary>");
        sb.Append(i2).AppendLine("/// Routes an incoming media frame to the appropriate per-stream virtual method.");
        sb.Append(i2).AppendLine("/// Call this from <see cref=\"global::CulpeoStream.AspNetCore.ICulpeoStreamHandler.OnMediaFrameAsync\"/>.");
        sb.Append(i2).AppendLine("/// </summary>");
        sb.Append(i2).AppendLine("public global::System.Threading.Tasks.Task HandleMediaAsync(");
        sb.Append(i2).AppendLine("    string streamId,");
        sb.Append(i2).AppendLine("    global::System.ReadOnlyMemory<byte> payload,");
        sb.Append(i2).AppendLine("    long offset,");
        sb.Append(i2).AppendLine("    global::System.Threading.CancellationToken cancellationToken = default)");
        sb.Append(i2).AppendLine("    => streamId switch");
        sb.Append(i2).AppendLine("    {");
        foreach (var stream in descriptor.Streams)
        {
            var methodName = $"On{stream.SafeMethodSuffix}Async";
            sb.Append(i3).Append($"\"{EscapeString(stream.Id)}\" => {methodName}(payload, offset, cancellationToken),").AppendLine();
        }
        sb.Append(i3).AppendLine("_ => OnUnknownStreamAsync(streamId, payload, offset, cancellationToken),");
        sb.Append(i2).AppendLine("    };");

        // ── Virtual stubs for event handlers ─────────────────────────────

        sb.AppendLine();
        sb.Append(i2).AppendLine("// ── Protocol event stubs — override to handle specific protocol messages ─────");

        foreach (var evt in ProtocolEvents)
        {
            var methodName = EventToMethodName(evt);
            sb.Append(i2).AppendLine($"/// <summary>Called when event <c>\"{evt}\"</c> is received. Override to handle it.</summary>");
            sb.Append(i2).AppendLine($"protected virtual global::System.Threading.Tasks.Task {methodName}(string jsonBody, global::System.Threading.CancellationToken cancellationToken)");
            sb.Append(i2).AppendLine($"    => global::System.Threading.Tasks.Task.CompletedTask;");
            sb.AppendLine();
        }

        sb.Append(i2).AppendLine("/// <summary>Called for unrecognised event names. Override to handle custom application events.</summary>");
        sb.Append(i2).AppendLine("protected virtual global::System.Threading.Tasks.Task OnUnknownEventAsync(string eventName, string jsonBody, string? streamId, global::System.Threading.CancellationToken cancellationToken)");
        sb.Append(i2).AppendLine("    => global::System.Threading.Tasks.Task.CompletedTask;");

        // ── Per-stream media stubs ────────────────────────────────────────

        if (descriptor.Streams.Length > 0)
        {
            sb.AppendLine();
            sb.Append(i2).AppendLine("// ── Per-stream media handler stubs — override to process media frames ────────");

            foreach (var stream in descriptor.Streams)
            {
                var methodName = $"On{stream.SafeMethodSuffix}Async";
                sb.Append(i2).AppendLine($"/// <summary>Called for media frames on stream <c>\"{EscapeString(stream.Id)}\"</c> ({stream.ContentType}). Override to process frames.</summary>");
                sb.Append(i2).AppendLine($"protected virtual global::System.Threading.Tasks.Task {methodName}(global::System.ReadOnlyMemory<byte> payload, long offset, global::System.Threading.CancellationToken cancellationToken)");
                sb.Append(i2).AppendLine($"    => global::System.Threading.Tasks.Task.CompletedTask;");
                sb.AppendLine();
            }
        }

        sb.AppendLine();
        sb.Append(i2).AppendLine("/// <summary>Called for media frames on unknown or unregistered stream IDs.</summary>");
        sb.Append(i2).AppendLine("protected virtual global::System.Threading.Tasks.Task OnUnknownStreamAsync(string streamId, global::System.ReadOnlyMemory<byte> payload, long offset, global::System.Threading.CancellationToken cancellationToken)");
        sb.Append(i2).AppendLine("    => global::System.Threading.Tasks.Task.CompletedTask;");

        sb.Append(indent).AppendLine("}");

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string EventToMethodName(string eventName)
    {
        // "culpeo.init" → "OnCulpeoInitAsync"
        // "culpeo.init-ack" → "OnCulpeoInitAckAsync"
        var sb = new StringBuilder("On");
        bool capitalizeNext = true;
        foreach (char c in eventName)
        {
            if (c == '.' || c == '-')
            {
                capitalizeNext = true;
            }
            else if (char.IsLetterOrDigit(c))
            {
                sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }
        }
        sb.Append("Async");
        return sb.ToString();
    }

    private static string StreamTypeExpression(int streamType) => streamType switch
    {
        0 => "global::CulpeoStream.Core.CulpeoStreamType.Input",
        1 => "global::CulpeoStream.Core.CulpeoStreamType.Output",
        2 => "global::CulpeoStream.Core.CulpeoStreamType.Duplex",
        _ => "global::CulpeoStream.Core.CulpeoStreamType.Input",
    };

    private static string OffsetTypeExpression(int offsetType) => offsetType switch
    {
        0 => "global::CulpeoStream.Core.OffsetType.Time",
        1 => "global::CulpeoStream.Core.OffsetType.Byte",
        2 => "global::CulpeoStream.Core.OffsetType.Message",
        _ => "global::CulpeoStream.Core.OffsetType.Byte",
    };

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
