"""
Type stubs for the CulpeoStream Python extension module.

Generated by hand for culpeostream v0.1.0 (pybind11 bindings over the C++ core).
Run ``pybind11-stubgen culpeostream`` after installation to regenerate from
the live module.
"""

from __future__ import annotations

from enum import IntEnum
from typing import Optional, Dict, Tuple, Callable

# ─── Enums ────────────────────────────────────────────────────────────────────

class FrameType(IntEnum):
    """Frame type: control (text WebSocket frame) or media (binary frame)."""
    control: int
    """Control frame (text); carries events, init, ping, etc."""
    media: int
    """Media frame (binary); carries audio/video payload."""

class OffsetType(IntEnum):
    """Stream offset increment strategy (spec §5.5)."""
    time: int
    """PCM sample-count offset (requires audio/pcm)."""
    byte: int
    """Raw byte-length offset."""
    message: int
    """Per-frame increment."""

class SessionState(IntEnum):
    """Session lifecycle state machine states."""
    uninitialized: int
    """Transport connected; awaiting culpeo.init."""
    initializing: int
    """culpeo.init received; validation in progress."""
    established: int
    """culpeo.init-ack sent; session active."""
    closed: int
    """Session is terminated."""

# ─── ParseLimits ──────────────────────────────────────────────────────────────

class ParseLimits:
    """Configurable limits for the frame parser."""
    max_header_block_bytes: int  # default: 8192
    max_header_value_bytes: int  # default: 4096
    max_header_count: int        # default: 64

    def __init__(self) -> None: ...

# ─── CulpeoMessage ────────────────────────────────────────────────────────────

class CulpeoMessage:
    """Parsed CulpeoStream frame.

    Construct from raw bytes; the constructor parses the header block and body.
    All header values are copied into Python objects.

    Args:
        data:       Raw frame bytes (header block + CRLF CRLF + body).
        frame_type: FrameType.control (default) or FrameType.media.
        limits:     ParseLimits (optional; uses 8 KiB defaults).

    Raises:
        ValueError: If the frame is malformed (missing terminator, invalid
                    header names, block too large, etc.).
    """

    def __init__(
        self,
        data: bytes,
        frame_type: FrameType = FrameType.control,
        limits: Optional[ParseLimits] = None,
    ) -> None: ...

    def type(self) -> FrameType:
        """Return the FrameType of this message."""
        ...

    def headers(self) -> Dict[str, str]:
        """Return a dict of all present well-known headers.

        Keys include: ``Event``, ``Content-Type``, ``Authorization``,
        ``Session-Id``, ``Stream-Id``, ``Offset``, ``Timestamp``,
        ``Buffer-Window``, ``Reason``, ``Code``.

        .. warning::
            The ``Authorization`` header contains a bearer token.
            Do **not** log or persist this value (spec §A.6).
        """
        ...

    def body(self) -> bytes:
        """Return the message body as bytes."""
        ...

# ─── WsTransport ──────────────────────────────────────────────────────────────

class WsTransport:
    """Python-callback-backed WebSocket transport.

    Wraps the C++ WsTransport with injected Python callables.  Pass an
    instance of this class to :class:`Session`.

    All callbacks are invoked with the GIL acquired, so they may safely call
    Python code and access Python objects.

    Args:
        on_send_text:   Called when a control frame is sent. Signature: ``(data: bytes) -> None``.
        on_send_binary: Called when a media frame is sent. Signature: ``(data: bytes) -> None``.
        on_close:       Called on close. Signature: ``(code: int, reason: str) -> None``.
    """

    def __init__(
        self,
        on_send_text: Callable[[bytes], None],
        on_send_binary: Callable[[bytes], None],
        on_close: Callable[[int, str], None],
    ) -> None: ...

# ─── SessionConfig ────────────────────────────────────────────────────────────

class SessionConfig:
    """Protocol configuration for a session."""
    max_buffer_window_ms: int       # default: 30_000
    default_buffer_window_ms: int   # default: 5_000
    max_streams: int                # default: 16
    max_ping_rate_per_second: int   # default: 5
    auth_refresh_timeout_s: int     # default: 30
    supported_versions: list[str]   # default: ["0.3"]

    def __init__(self) -> None: ...

# ─── Session ──────────────────────────────────────────────────────────────────

class Session:
    """CulpeoStream server-side session.

    Manages the session lifecycle.  All methods are thread-safe.

    I/O methods release the GIL, so they do not block the Python event loop or
    other threads.

    Callbacks from C++ (on_auth_validate, on_media_received, on_close, on_rtt,
    on_auth_response) are invoked with the GIL acquired.

    Args:
        transport:          :class:`WsTransport` instance.  The transport object
                            must remain alive for the lifetime of this Session.
        on_auth_validate:   ``Callable[[str], bool]`` — validate the bearer token.
                            **Required** for auth enforcement.
        on_media_received:  ``Callable[[str, int, bytes], None]`` — called with
                            ``(stream_id, timestamp_us, body)`` for each received
                            media frame.  Optional.
        on_close:           ``Callable[[str, str], None]`` — called with
                            ``(code, reason)`` when the session closes.  Optional.
        on_rtt:             ``Callable[[int], None]`` — called with RTT in
                            microseconds after each pong.  Optional.
        on_auth_response:   ``Callable[[str], bool]`` — validate the new token
                            in a culpeo.auth-response.  Required for auth-refresh.
        config:             :class:`SessionConfig` (optional).
    """

    def __init__(
        self,
        transport: WsTransport,
        on_auth_validate: Optional[Callable[[str], bool]] = None,
        on_media_received: Optional[Callable[[str, int, bytes], None]] = None,
        on_close: Optional[Callable[[str, str], None]] = None,
        on_rtt: Optional[Callable[[int], None]] = None,
        on_auth_response: Optional[Callable[[str], bool]] = None,
        config: SessionConfig = ...,
    ) -> None: ...

    def state(self) -> SessionState:
        """Return the current session state."""
        ...

    def session_id(self) -> Optional[str]:
        """Return the server-assigned session ID (32-char hex), or None."""
        ...

    def process_control_frame(self, data: bytes) -> None:
        """Feed a raw control frame (bytes).

        Parses headers and processes the event (e.g. culpeo.init, culpeo.ping).
        Releases the GIL during processing.

        Raises:
            ValueError:    If the frame is malformed.
            RuntimeError:  If the frame is valid but the session rejected it
                           (wrong state, auth failure, etc.).
        """
        ...

    def process_media_frame(self, data: bytes) -> None:
        """Feed a raw media frame (bytes).

        Validates the stream ID and offset, then fires on_media_received.
        Releases the GIL during processing.

        Raises:
            ValueError:    If the frame is malformed.
            RuntimeError:  If the frame is rejected by the session.
        """
        ...

    def send_media(
        self,
        stream_id: str,
        payload: bytes,
        timestamp_us: int = 0,
    ) -> None:
        """Send a media payload on a server-output or duplex stream.

        Releases the GIL during the I/O call.

        Raises:
            RuntimeError: If the session is not established or the stream is
                          not writable.
        """
        ...

    def send_ping(self) -> None:
        """Send a culpeo.ping.  RTT is reported via on_rtt callback."""
        ...

    def close(self, code: str = "normal", reason: str = "Closing") -> None:
        """Initiate graceful session close.  Releases the GIL."""
        ...

# ─── H2Client ─────────────────────────────────────────────────────────────────

class H2Client:
    """HTTP/2 CulpeoStream client.

    All methods are synchronous and release the GIL while waiting.

    Args:
        cleartext: If True (default), use h2c (no TLS) — for tests only.
                   If False, TLS with system CA verification.
    """

    def __init__(self, cleartext: bool = True) -> None: ...

    def connect(self, host: str, port: str, path: str = "/") -> None:
        """Open the HTTP/2 connection and submit the POST request."""
        ...

    def send_text(self, data: bytes) -> None:
        """Send a control frame.  Type octet 0x01 is prepended automatically."""
        ...

    def send_binary(self, data: bytes) -> None:
        """Send a media frame.  Type octet 0x02 is prepended automatically."""
        ...

    def receive_frame(self) -> Tuple[int, bytes]:
        """Block and receive the next frame.

        Returns:
            A tuple ``(type_byte, payload)`` where ``type_byte`` is 0x01
            (control) or 0x02 (media).
        """
        ...

    def close_session(self) -> None:
        """Send GOAWAY and close the HTTP/2 connection."""
        ...

# ─── H2Server ─────────────────────────────────────────────────────────────────

class ServerTransport:
    """Per-session bidirectional transport returned by :meth:`H2Server.accept`.

    All I/O methods release the GIL while blocking.
    ``receive_frame()`` raises ``StopIteration`` when the session closes.
    """

    @property
    def is_valid(self) -> bool:
        """False after the remote side has closed the session."""
        ...

    def receive_frame(self) -> Tuple[int, bytes]:
        """Block and receive the next frame.

        Returns:
            A tuple ``(type_byte, payload)``.

        Raises:
            StopIteration: When the session is closed.
        """
        ...

    def send_text(self, data: bytes) -> None:
        """Send a control frame."""
        ...

    def send_binary(self, data: bytes) -> None:
        """Send a media frame."""
        ...

    def close_transport(self, code: int = 1000, reason: str = "normal") -> None:
        """Close the HTTP/2 stream."""
        ...

class H2Server:
    """HTTP/2 CulpeoStream server.

    Accepts connections and queues sessions for Python to consume via
    :meth:`accept`.

    Args:
        port:      TCP port to listen on (0 = OS-assigned).
        cleartext: If True (default), use h2c (no TLS).  TLS servers require
                   certificate configuration (not yet exposed in the Python API).
    """

    def __init__(self, port: int = 0, cleartext: bool = True) -> None: ...

    @property
    def port(self) -> int:
        """The bound TCP port (useful when port 0 was passed)."""
        ...

    def accept(self) -> Optional[ServerTransport]:
        """Block until the next client session connects.

        Returns:
            A :class:`ServerTransport` for the new session, or ``None`` if the
            server has been stopped.
        """
        ...

    def stop(self) -> None:
        """Stop accepting new connections and unblock any pending accept()."""
        ...
